version: '3'

services:
  api:
    build:
      context: .
      dockerfile: .deployment/api/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./www:/app

  frontend:
    build:
      context: .
      dockerfile: .deployment/frontend/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./www:/app
